[package]
name = "rsgrad-nn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsgrad-primitive = {path = "../rsgrad-primitive"}
rand = "0.8.5"
